Starter View Implementation
swiftmumbai/chatkit pull request #7
Opened 2019-10-10 08:35 UTC by tlimaye91

1. I have added a constant file for storing custom colours. 
2. In sceneDelegate file I have changed ContentView to StarterView. 
3. UI implementation of StarterView. 
4. As of now, I have used system fonts. ( I can change it when you will provide the font)
5. As of now, I have crop the "loginlogo" from assets. ( I can change it when you will provide the images).

Please take a look.

2019-10-10 11:18 UTC, tlimaye91 commented on Chatkit/Chatkit/SceneDelegate.swift
>              self.window = window
Changed ContentView to Starter View

2019-10-10 13:11 UTC, rajhraval requested changes
- Seems identical to the Asset provided.
- The Font used is Rubik. (Add it)
- Color Hex Value is 2567FF

Then It's good to go.

2019-10-10 16:41 UTC, tlimaye91 commented
I have updated on the below points - 
1. Seems identical to the Asset provided. 
2. The Font used is Rubik. (Add it)
3. Color Hex Value is 2567FF

2019-10-13 15:45 UTC, rajhraval approved these changes
Looks fine, good to go!

2019-10-14 07:46 UTC, ygit approved these changes
Looks good to merge 👏🎉

2019-10-14 07:46 UTC, ygit commented
@tlimaye91 Go ahead, `Squash & Merge` the PR

2019-10-14 09:31 UTC, tlimaye91 commented
@ygit I don't think I have "write" access to merge.

2019-10-14 09:42 UTC, merged